# Generated by Django 2.2.11 on 2020-05-21 16:57
from typing import List
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: List[str] = []

    operations = [
        migrations.CreateModel(
            name='otp',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('secret', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'otp',
            },
        ),
    ]
